# Generated by Django 4.2.7 on 2025-11-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_yearlysummary_alter_dailysummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buying Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price'),
        ),
    ]
