# Generated by Django 4.2.7 on 2025-11-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AlterModelOptions(
            name='dailysummary',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
